theme: jekyll-theme-minimal
locale: ja-JP
title: BFU2Sサポート
logo: https://bit-trade-one.co.jp/wp/wp-content/uploads/2022/05/BFU2S.jpg
description: USBデュアルコネクトカスタムキーパッドのサポートサイトです。
show_downloads: false
